version: '3.7'
services:
  mysql_service:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    command: --innodb_use_native_aio=0
    volumes:
      - ./data:/var/lib/mysql
      - ./initDb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass